### ISSUE TITLE
Corrupt resources on Linux & Windows?

### ISSUE THREAD

**Issue by coelhucas** [firebelley/godot-export#132]
I've been using the action on my two 3.X commercial games, without any issues. On my current project, though, I've been facing some issues generating Linux & Windows &mdash; I use a macOS, but since the action runs on an Ubuntu, I don't think this should be the issue, unless the problem is in Godot itself.

If locally built, the project work on the three platforms.

But when generated on the action, I can see these logs:

| Windows | Linux/X11 | Mac OS |
-- | -- | --
![image](https://github.com/firebelley/godot-export/assets/28108272/b79ad46b-c97d-4ef9-87d4-fcb63ee76522) | ![image](https://github.com/firebelley/godot-export/assets/28108272/6ea433fd-1e1f-4dc8-90d5-c4b292261db8) | ![image](https://github.com/firebelley/godot-export/assets/28108272/c2ddb402-cd53-435d-a87c-882b4ba27a12)

(There's ~2k lines of errors/warnings for basically *every* resource on the project for both windows and linux)

For both Windows & Linux, those builds will open, show Godot's splash and close. The generated logs show the same erros from these action ones.

On MacOS, although having this custom cursor thing, it works perfectly.

**Comment by ProFiLeR4100** [comment]
I've had similar error messages, but it was because I've forgot that my repo was using LFS.
So I've added additional step after checkout, here how it looks like:

```yaml
  - name: Checkout
    uses: actions/checkout@v3.3.0
    with:
      lfs: true
      submodules: recursive

  - name: Download files from Git LFS
    run: git lfs pull
```
