### ISSUE TITLE
Headless mirror?

### ISSUE THREAD

**Issue by arkuhn** [firebelley/godot-export#140]
The recommended [host ](http://downloads.tuxfamily.org/)of the executable no longer seems to work (connection timeout) and poking around on the forum they seem[ to be dead](https://forum.tuxfamily.org/post/3381/#p3381) according to the maintainers. Could the example in the README site a working alternative (if one exists?) thanks in advance! and apologies that this is mostly about an upstream issue.

**Comment by raffomania** [comment]
I've changed our CI to use github instead:
```yaml
- name: export game
    uses: firebelley/godot-export@v6.0.0
    with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_BUILD }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_BUILD }}_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_BUILD }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_BUILD }}_export_templates.tpz
    # ...
```
