### ISSUE TITLE
Failed to change the icon

### ISSUE THREAD

**Issue by Lemonbrush** [firebelley/godot-export#142]
Here is my code. For some reason it does not change the exe's icon

```
name: Test exe icon export

on: [push]

jobs:
  export-game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

      - name: Export Game using Godot
        uses: firebelley/godot-export@v4.1.1
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/3.5.1-stable/Godot_v3.5.1-stable_linux_headless.64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/3.5.1-stable/Godot_v3.5.1-stable_export_templates.tpz"
          relative_project_path: ./
          archive_output: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: /home/runner/.local/share/godot/archives/Windows Desktop.zip
```
