### ISSUE TITLE
Error during first build: not a directory, scandir 

### ISSUE THREAD

**Issue by h4de5** [firebelley/godot-export#2]
I wanted to try out this action, but got the following error:

 ```
export game
Run firebelley/godot-export@v1.0.0
  with:
    base_version: 0.0.1
    godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_linux_headless.64.zip
    godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_export_templates.tpz
    relative_project_path: ./
    godot_template_version: 3.1.2.stable
  env:
    GITHUB_TOKEN: ***
Using release version v0.0.1
Working path created /home/runner/.local/share/godot
Godot setup
  Downloading Godot executable from https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_linux_headless.64.zip
  Downloading Godot export templates from https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_export_templates.tpz
  /usr/bin/wget -nv https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_linux_headless.64.zip -O /home/runner/.local/share/godot/godot.zip
  /usr/bin/wget -nv https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_export_templates.tpz -O /home/runner/.local/share/godot/godot_templates.tpz
  2020-01-16 22:52:32 URL:https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_linux_headless.64.zip [25055920/25055920] -> "/home/runner/.local/share/godot/godot.zip" [1]
  /usr/bin/unzip -q /home/runner/.local/share/godot/godot.zip -d /home/runner/.local/share/godot/godot_executable
  Found executable in /home/runner/.local/share/godot/godot_executable/Godot_v3.1.2-stable_linux_headless.64
##[error]ENOTDIR: not a directory, scandir '/home/runner/.local/share/godot/godot_executable/Godot_v3.1.2-stable_linux_headless.64'
##[error]ENOTDIR: not a directory, scandir '/home/runner/.local/share/godot/godot_executable/Godot_v3.1.2-stable_linux_headless.64'
##[error]Node run failed with exit code 1
```

can you tell me which directory it does not find?

my workflow yml:
```
name: CI

# Whenever a push is made to the master branch then run the job
on:
  push:
    branches:
      - master

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Job name, can be anything
    name: Export Game Job
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v1
    - name: export game
      # Use version 1.0.0 (see releases for all versions)
      uses: firebelley/godot-export@v1.0.0
      with:
        # Base version. Patch versions are incremented when this action runs.
        base_version: 0.0.1
        # The download url of the 64 bit Linux Headless Godot executable
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_linux_headless.64.zip
        # The url of the export templates corresponding to the Godot executable version
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_export_templates.tpz
        # The relative path containing the "project.godot" file
        relative_project_path: ./
        # The name of the folder which templates are stored in. Looks like '3.1.1.stable.mono'. Can be found at %APPDATA\Roaming\Godot\templates on Windows and ~/.local/share/godot/templates on Linux.
        godot_template_version: 3.1.2.stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

my export_presets.cfg:
```
[preset.0]

name="Family Tree win"
platform="Windows Desktop"
runnable=false
custom_features=""
export_filter="all_resources"
include_filter="settings.cfg"
exclude_filter="_familytree/*,_familytree/Stammbaum*Media/*"
export_path="dist/godot-familytree.exe"
patch_list=PoolStringArray(  )
script_export_mode=1
script_encryption_key=""

[preset.0.options]

texture_format/bptc=false
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=true
texture_format/no_bptc_fallbacks=true
binary_format/64_bits=true
custom_template/release=""
custom_template/debug=""
application/icon=""
application/file_version=""
application/product_version=""
application/company_name=""
application/product_name="Godot Family Tree"
application/file_description="Godot Family Tree"
application/copyright=""
application/trademarks=""

[preset.1]

name="Family Tree web"
platform="HTML5"
runnable=false
custom_features=""
export_filter="all_resources"
include_filter="settings.cfg"
exclude_filter="_familytree/*,_familytree/Stammbaum*Media/*"
export_path="dist/godot-familytree.html"
patch_list=PoolStringArray(  )
script_export_mode=1
script_encryption_key=""

[preset.1.options]

vram_texture_compression/for_desktop=true
vram_texture_compression/for_mobile=true
html/custom_html_shell=""
html/head_include=""
custom_template/release=""
custom_template/debug=""

[preset.2]

name="Family Tree linux"
platform="Linux/X11"
runnable=false
custom_features=""
export_filter="all_resources"
include_filter="settings.cfg"
exclude_filter="_familytree/*,_familytree/Stammbaum*Media/*"
export_path="dist/godot-familytree"
patch_list=PoolStringArray(  )
script_export_mode=1
script_encryption_key=""

[preset.2.options]

texture_format/bptc=false
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=true
texture_format/no_bptc_fallbacks=true
binary_format/64_bits=true
custom_template/release=""
custom_template/debug=""
```

Link to repository in case you want to check something else: 
https://github.com/h4de5/godot-familytree
