### ISSUE TITLE
Workflow action doesn't read export path

### ISSUE THREAD

**Issue by BluePhoenixGame** [firebelley/godot-export#25]
We have a game were we want to automatically deploy it with github pages, but we're encountering an issue regarding export path.
```
rsync: change_dir "/home/runner/work/crackout/crackout//HTML5/" failed: No such file or directory (2)
````
is the error we get, because this is the export path we set in export_presets.cfg.
But this is not the path were our game is exported. If we go up we can see it's exported here
```
/home/runner/.local/share/godot/godot_executable/Godot_v3.2.2-stable_mono_linux_headless_64/godot /home/runner/work/crackout/crackout/project.godot --export HTML5 /home/runner/.local/share/godot/builds/HTML5/index.html --verbose
```
More specifically here: `/home/runner/.local/share/godot/builds/HTML5/index.html`
While we expect it to be exported to our chosen path here:
`/home/runner/work/crackout/crackout/HTML5/` (Rather have it at `home/runner/crackout/HTML5` but that's another issue)

Here is our deployment.yml
```
name: Deployment

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  export_game:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Export
      uses: firebelley/godot-export@v2.2.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2-stable_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2-stable_mono_export_templates.tpz
        relative_project_path: ./
        create_release: false
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ../../../.local/share/godot/builds/HTML5/
        TARGET_FOLDER: ${GITHUB_REF##*/}/game/
        CLEAN: true
```
Now, in this yml we include the fix which is rather disgusting `../../../.local/share/godot/builds/HTML5/`. And well, frankly this is not desired. Our export_presets.cfg looks like this: 
```
[preset.0]

name="HTML5"
platform="HTML5"
runnable=true
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="HTML5/index.html"
patch_list=PoolStringArray(  )
script_export_mode=1
script_encryption_key=""

[preset.0.options]

vram_texture_compression/for_desktop=true
vram_texture_compression/for_mobile=false
html/custom_html_shell=""
html/head_include=""
custom_template/release=""
custom_template/debug=""
```
