### ISSUE TITLE
Unable to locate executable file: godot.

### ISSUE THREAD

**Issue by knightofiam** [firebelley/godot-export#43]
Here's the relevant part of my yaml:

```
on:
  push:
    branches:
      - master

jobs:
  export:
    name: export executables
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: create executables
        uses: firebelley/godot-export@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GODOT_MONO_VERSION: 3.2.2
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_MONO_VERSION}}/mono/Godot_v${{env.GODOT_MONO_VERSION}}-stable_mono_linux_headless_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_MONO_VERSION}}/mono/Godot_v${{env.GODOT_MONO_VERSION}}-stable_mono_export_templates.tpz
          relative_project_path: ./
          use_preset_export_path: true
          archive_export_output: true
          create_release: true
          base_version: 0.0.1
```

Here's the relevant part of the log:

```
  env:
    GITHUB_TOKEN: ***
    GODOT_MONO_VERSION: 3.2.2
Download Godot
  Working path created /home/runner/.local/share/godot
  Downloading Godot export templates from https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2-stable_mono_export_templates.tpz
  Downloading Godot executable from https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2-stable_mono_linux_headless_64.zip
  /usr/bin/wget -nv https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2-stable_mono_export_templates.tpz -O /home/runner/.local/share/godot/godot_templates.tpz
  /usr/bin/wget -nv https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2-stable_mono_linux_headless_64.zip -O /home/runner/.local/share/godot/godot.zip
  2020-12-02 06:25:34 URL:https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2-stable_mono_export_templates.tpz [623608361/623608361] -> "/home/runner/.local/share/godot/godot_templates.tpz" [1]
  Error: Unable to locate executable file: godot. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

The environment-variable-injected URL's are correct because I can download the files directly from them in the log.
