### ISSUE TITLE
If relative_project_path is set, it should be appended when use_preset_export_path

### ISSUE THREAD

**Issue by tom-leys** [firebelley/godot-export#68]
In Godot, if you export from a folder it is relative to res:// root.

The same should happen when you use this action.

With these settings, outputs go in /build/ (as specified in my exports file) where they should go in /game/build

```
- name: export game
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@55461c5b671a5aea2ffdc01f0f3c131b5f87cabe
        with:
          # Use 3.3.2. Need Linux headless for building.
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.3.3/Godot_v3.3.3-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.3.3/Godot_v3.3.3-stable_export_templates.tpz
          relative_project_path: ./game/
          use_preset_export_path: true
          # relative_export_path: ./game/build/win/
          archive_export_output: false
          create_release: false
  #        base_version:  ${{ steps.tag_version.outputs.TAG_VERSION}} 
          export_debug: true
```
