### ISSUE TITLE
Release notes show only last commit

### ISSUE THREAD

**Issue by rafallus** [firebelley/godot-export#71]
I'm using tags to generate my project's executable. The script I'm using is taken directly from the examples:
<details>
  <summary>Workflow script</summary>

  ```
# Whenever tag in the form of `v1.0.0` is pushed then run the job

on:
  push:
    tags:
      - 'v*'

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Job name, can be anything
    name: Export Game Job
    steps:
      # Always include the checkout step so that
      # your project is available for Godot to export
    - name: install wine
      id: wine_install
      run: |
        sudo apt install wine64
        echo ::set-output name=WINE_PATH::$(which wine64)
    - name: checkout
      uses: actions/checkout@v2.3.1
      # Ensure that you get the entire project history
      with:
        fetch-depth: 0
      # separate step to extract the version from the tag name
    - name: get tag from version
      id: tag_version
      run: |
        echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}
    - name: export game
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v3.0.0
      with:
        # Defining all the required inputs
        # I used the mono version of Godot in this example
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4.2/Godot_v3.4.2-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4.2/Godot_v3.4.2-stable_export_templates.tpz
        relative_project_path: ./
        create_release: true
        base_version:  ${{ steps.tag_version.outputs.TAG_VERSION}}
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ```
</details>

Whenever I push a new tag, the generated release notes are only showing the description from the last commit. Is this expected? How can it take into account all the commits since the last tag I've pushed?
